server:
  address: localhost
  port: 8280

jwt:
  public-key: src/main/resources/public_key.pem
  private-key: src/main/resources/private_key.pem

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:websiteDB;DB_CLOSE_DELAY=-1;
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: websitemaster591@gmail.com
    password: jienladpiydxyyds
    properties:
      smtp:
        socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory
        auth: true
        starttls:
          enable: true



mail:
  store:
    protocol: imap
  imap:
    host: imap.gmail.com
    port: 993

contacts: src/main/resources/Contacts.json
login-message: src/main/resources/LoginMessage.txt
front-end-link: http://localhost:5200/activation
paypal:
  client-id: AdA9PkraPr9pDbfPjB4rUMH1_R2wHQGVggNOUY3Mz7frFOSwzVW7Hx6NexOyeO7AfkFUE-0DD1ij42To
  client-secret: ELwVOk1nH1cAcUtlWWjBafMUyqSRyRv_YAdByemK18__cv2otLA5rh_TZuD3EbzZ_5YGdwqS5AECNahz
  mode: sandbox
  merchant-info: sb-vgbuv37296565@business.example.com

github:
  client_id: Ov23liETvhWUY8zJj9ko
  client_secret: 459e04eebe687772f352ccfaeb711ca89abc080d
